---

- include_tasks: os_RedHat.yml
  when: ansible_facts.os_family == "RedHat"
  tags:
    - configuration
    - docker_storage

- include_tasks: os_Debian.yml
  when: ansible_facts.os_family == "Debian"
  tags:
    - configuration
    - docker_storage
